# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER learn-drive

# 挂载目录
VOLUME /home/learn-drive
# 创建目录
RUN mkdir -p /home/learn-drive
# 指定路径
WORKDIR /home/learn-drive
# 复制jar文件到路径
COPY ./jar/learn-drive-modules-job.jar /home/learn-drive/learn-drive-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","learn-drive-modules-job.jar"]