# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/learn-drive
# 创建目录
RUN mkdir -p /home/learn-drive
# 指定路径
WORKDIR /home/learn-drive
# 复制jar文件到路径
COPY ./jar/learn-drive-visual-monitor.jar /home/ruoyi/learn-drive-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","learn-drive-visual-monitor.jar"]